version: "3.4"

services:
  web:
    image: export-excel:1.0
    build:
      # context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    hostname: export.tirtasatria.tech
    networks:
      - back-tier

networks:
  back-tier:
    external: true
