// import "./globals.css";
// import { Inter } from 'next/font/google'
import AppwriteSessionProvider from "@components/commons/provider/session";
import { cookies } from "next/dist/client/components/headers";
import { Public_Sans as PublicSans } from "next/font/google";
import { sessionNames } from "src/lib";

// const inter = Inter({ subsets: ['latin'] })
const inter = PublicSans({
	subsets: ["latin"],
	weight: ["300", "400", "500", "700"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const cookie = cookies();
	return (
		<html lang="en">
			<body
				className={inter.className}
				style={{
					backgroundColor: "rgb(239 239 241)",
				}}
			>
				{cookie.has(sessionNames[0]) || cookie.has(sessionNames[1]) ? (
					<AppwriteSessionProvider />
				) : null}
				{children}
			</body>
		</html>
	);
}
