version: "3.4"

services:
    kpi-staging:
        build:
            context: ../../
            dockerfile: docker/staging/Dockerfile
        image: kpi-staging
        ports:
            - 3004:3000
        hostname: staging-kpi.tirtasatria.tech
        networks:
            - back-tier

networks:
    back-tier:
        external: true
