version: "3.4"

services:
    kpi-staging:
        container_name: staging-kpi
        build:
            context: ../../
            dockerfile: docker/staging/Dockerfile
        image: kpi-staging
        ports:
            - 3004:3000
        #hostname: staging-kpi.tirtasatria.tech
        environment:
            - HOSTNAME=localhost
        networks:
            - back-tier

networks:
    back-tier:
        external: true
